# Generated by Django 3.0.7 on 2020-06-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=400)),
                ('deployment', models.CharField(max_length=400)),
                ('image', models.CharField(max_length=400)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
